### Reading in URA property prices dataset from JSON

In [1]:
import json
import pandas as pd
import requests

In [2]:
import os
from google.colab import drive
drive.mount('/content/drive') # Added shortcut to drive
%cd "/content/drive/My Drive/IS4242/notebooks"

Mounted at /content/drive
/content/drive/.shortcut-targets-by-id/1MQLnt9GVYxbI3RwgVSJ5kXNFD4tFaGMJ/IS4242/notebooks

In [3]:
with open('Private Residential Property Transactions.json', 'r') as f:
    data = json.loads(f.read())

# Flatten data
df = pd.json_normalize(data, record_path=['Result'])
df

,street,x,project,y,transaction,marketSegment
0,ZEHNDER ROAD,22734.9253,LANDED HOUSING DEVELOPMENT,29502.42071,"[{'area': '524.3', 'floorRange': '-', 'noOfUni...",RCR
1,NEO PEE TECK LANE,20914.1988965525,LANDED HOUSING DEVELOPMENT,30589.1070785135,"[{'area': '159.3', 'floorRange': '-', 'noOfUni...",RCR
2,COVE DRIVE,28382.47067,TURQUOISE,25008.33592,"[{'area': '224', 'floorRange': '01-05', 'noOfU...",CCR
3,BUKIT TERESA ROAD,27054.52601,LANDED HOUSING DEVELOPMENT,28712.63181,"[{'area': '435.2', 'floorRange': '-', 'noOfUni...",RCR
4,ALEXANDRA VIEW,26204.50079,ARTRA,30270.56219,"[{'area': '114', 'floorRange': '21-25', 'noOfU...",RCR
...,...,...,...,...,...,...
289,COVE GROVE,28366.75045,LANDED HOUSING DEVELOPMENT,24714.72787,"[{'area': '852.6', 'floorRange': '-', 'noOfUni...",CCR
290,ALEXANDRA VIEW,26074.4211,THE METROPOLITAN CONDOMINIUM,30319.95369,"[{'area': '130', 'floorRange': '01-05', 'noOfU...",RCR
291,WESTRIDGE WALK,23178.2986,LANDED HOUSING DEVELOPMENT,28916.22014,"[{'area': '214.1', 'floorRange': '-', 'noOfUni...",RCR
292,KIM TIAN ROAD,27603.58585,HIGHLINE RESIDENCES,29605.25187,"[{'area': '62', 'floorRange': '31-35', 'noOfUn...",RCR
293,FABER HEIGHTS,19547.85969,FABER CREST,33943.45546,"[{'area': '94', 'floorRange': '01-05', 'noOfUn...",OCR

In [4]:
# Expand transactions
df = df.explode('transaction').reset_index().drop(columns=['index'])
df

,street,x,project,y,transaction,marketSegment
0,ZEHNDER ROAD,22734.9253,LANDED HOUSING DEVELOPMENT,29502.42071,"{'area': '524.3', 'floorRange': '-', 'noOfUnit...",RCR
1,ZEHNDER ROAD,22734.9253,LANDED HOUSING DEVELOPMENT,29502.42071,"{'area': '308', 'floorRange': '-', 'noOfUnits'...",RCR
2,ZEHNDER ROAD,22734.9253,LANDED HOUSING DEVELOPMENT,29502.42071,"{'area': '314', 'floorRange': '-', 'noOfUnits'...",RCR
3,ZEHNDER ROAD,22734.9253,LANDED HOUSING DEVELOPMENT,29502.42071,"{'area': '308', 'floorRange': '-', 'noOfUnits'...",RCR
4,NEO PEE TECK LANE,20914.1988965525,LANDED HOUSING DEVELOPMENT,30589.1070785135,"{'area': '159.3', 'floorRange': '-', 'noOfUnit...",RCR
...,...,...,...,...,...,...
23698,FABER HEIGHTS,19547.85969,FABER CREST,33943.45546,"{'area': '96', 'floorRange': '01-05', 'noOfUni...",OCR
23699,FABER HEIGHTS,19547.85969,FABER CREST,33943.45546,"{'area': '94', 'floorRange': '01-05', 'noOfUni...",OCR
23700,FABER HEIGHTS,19547.85969,FABER CREST,33943.45546,"{'area': '173', 'floorRange': '01-05', 'noOfUn...",OCR
23701,FABER HEIGHTS,19547.85969,FABER CREST,33943.45546,"{'area': '94', 'floorRange': '01-05', 'noOfUni...",OCR
23702,FABER HEIGHTS,19547.85969,FABER CREST,33943.45546,"{'area': '125', 'floorRange': '01-05', 'noOfUn...",OCR

In [5]:
# Flatten transaction into columns
df2 = pd.json_normalize(df['transaction'])
merged = pd.merge(df, df2, left_index=True, right_index=True)
merged

,street,x,project,y,transaction,marketSegment,area,floorRange,noOfUnits,contractDate,typeOfSale,price,propertyType,district,typeOfArea,tenure,nettPrice
0,ZEHNDER ROAD,22734.9253,LANDED HOUSING DEVELOPMENT,29502.42071,"{'area': '524.3', 'floorRange': '-', 'noOfUnit...",RCR,524.3,-,1,0220,3,5500000,Semi-detached,05,Land,Freehold,NaN
1,ZEHNDER ROAD,22734.9253,LANDED HOUSING DEVELOPMENT,29502.42071,"{'area': '308', 'floorRange': '-', 'noOfUnits'...",RCR,308,-,1,0918,3,5000000,Semi-detached,05,Land,Freehold,NaN
2,ZEHNDER ROAD,22734.9253,LANDED HOUSING DEVELOPMENT,29502.42071,"{'area': '314', 'floorRange': '-', 'noOfUnits'...",RCR,314,-,1,0618,3,4750000,Semi-detached,05,Land,Freehold,NaN
3,ZEHNDER ROAD,22734.9253,LANDED HOUSING DEVELOPMENT,29502.42071,"{'area': '308', 'floorRange': '-', 'noOfUnits'...",RCR,308,-,1,0921,3,5200000,Semi-detached,05,Land,Freehold,NaN
4,NEO PEE TECK LANE,20914.1988965525,LANDED HOUSING DEVELOPMENT,30589.1070785135,"{'area': '159.3', 'floorRange': '-', 'noOfUnit...",RCR,159.3,-,1,0320,3,2630000,Terrace,05,Land,Freehold,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23698,FABER HEIGHTS,19547.85969,FABER CREST,33943.45546,"{'area': '96', 'floorRange': '01-05', 'noOfUni...",OCR,96,01-05,1,0822,3,1080000,Condominium,05,Strata,99 yrs lease commencing from 1996,NaN
23699,FABER HEIGHTS,19547.85969,FABER CREST,33943.45546,"{'area': '94', 'floorRange': '01-05', 'noOfUni...",OCR,94,01-05,1,0223,3,1150000,Condominium,05,Strata,99 yrs lease commencing from 1996,NaN
23700,FABER HEIGHTS,19547.85969,FABER CREST,33943.45546,"{'area': '173', 'floorRange': '01-05', 'noOfUn...",OCR,173,01-05,1,1022,3,1870000,Condominium,05,Strata,99 yrs lease commencing from 1996,NaN
23701,FABER HEIGHTS,19547.85969,FABER CREST,33943.45546,"{'area': '94', 'floorRange': '01-05', 'noOfUni...",OCR,94,01-05,1,1222,3,1150000,Condominium,05,Strata,99 yrs lease commencing from 1996,NaN
23702,FABER HEIGHTS,19547.85969,FABER CREST,33943.45546,"{'area': '125', 'floorRange': '01-05', 'noOfUn...",OCR,125,01-05,1,0222,3,1550000,Condominium,05,Strata,99 yrs lease commencing from 1996,NaN

In [6]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23703 entries, 0 to 23702
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   street         23703 non-null  object
 1   x              23702 non-null  object
 2   project        23703 non-null  object
 3   y              23702 non-null  object
 4   transaction    23703 non-null  object
 5   marketSegment  23703 non-null  object
 6   area           23703 non-null  object
 7   floorRange     23703 non-null  object
 8   noOfUnits      23703 non-null  object
 9   contractDate   23703 non-null  object
 10  typeOfSale     23703 non-null  object
 11  price          23703 non-null  object
 12  propertyType   23703 non-null  object
 13  district       23703 non-null  object
 14  typeOfArea     23703 non-null  object
 15  tenure         23703 non-null  object
 16  nettPrice      129 non-null    object
dtypes: object(17)
memory usage: 3.1+ MB

There is a transaction/ project with missing x, y coordinates, so we will manually fill its latitude and longitude information from Property Pages.

In [7]:
merged[merged.x.isna()]

,street,x,project,y,transaction,marketSegment,area,floorRange,noOfUnits,contractDate,typeOfSale,price,propertyType,district,typeOfArea,tenure,nettPrice
14251,EVERTON ROAD,NaN,ASIA GARDENS,NaN,"{'area': '12488', 'floorRange': '11-15', 'noOf...",RCR,12488,11-15,84,0418,3,343000000,Condominium,02,Strata,Freehold,NaN

Nett Price is null for most rows/ transactions so we remove it.

In [8]:
merged = merged.drop(columns=['transaction', 'nettPrice'])
merged

,street,x,project,y,marketSegment,area,floorRange,noOfUnits,contractDate,typeOfSale,price,propertyType,district,typeOfArea,tenure
0,ZEHNDER ROAD,22734.9253,LANDED HOUSING DEVELOPMENT,29502.42071,RCR,524.3,-,1,0220,3,5500000,Semi-detached,05,Land,Freehold
1,ZEHNDER ROAD,22734.9253,LANDED HOUSING DEVELOPMENT,29502.42071,RCR,308,-,1,0918,3,5000000,Semi-detached,05,Land,Freehold
2,ZEHNDER ROAD,22734.9253,LANDED HOUSING DEVELOPMENT,29502.42071,RCR,314,-,1,0618,3,4750000,Semi-detached,05,Land,Freehold
3,ZEHNDER ROAD,22734.9253,LANDED HOUSING DEVELOPMENT,29502.42071,RCR,308,-,1,0921,3,5200000,Semi-detached,05,Land,Freehold
4,NEO PEE TECK LANE,20914.1988965525,LANDED HOUSING DEVELOPMENT,30589.1070785135,RCR,159.3,-,1,0320,3,2630000,Terrace,05,Land,Freehold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23698,FABER HEIGHTS,19547.85969,FABER CREST,33943.45546,OCR,96,01-05,1,0822,3,1080000,Condominium,05,Strata,99 yrs lease commencing from 1996
23699,FABER HEIGHTS,19547.85969,FABER CREST,33943.45546,OCR,94,01-05,1,0223,3,1150000,Condominium,05,Strata,99 yrs lease commencing from 1996
23700,FABER HEIGHTS,19547.85969,FABER CREST,33943.45546,OCR,173,01-05,1,1022,3,1870000,Condominium,05,Strata,99 yrs lease commencing from 1996
23701,FABER HEIGHTS,19547.85969,FABER CREST,33943.45546,OCR,94,01-05,1,1222,3,1150000,Condominium,05,Strata,99 yrs lease commencing from 1996
23702,FABER HEIGHTS,19547.85969,FABER CREST,33943.45546,OCR,125,01-05,1,0222,3,1550000,Condominium,05,Strata,99 yrs lease commencing from 1996

In [11]:
%pip install pyproj
%pip install pandarallel

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pyproj in /usr/local/lib/python3.9/dist-packages (3.4.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.9/dist-packages (from pyproj) (2022.12.7)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pandarallel
  Downloading pandarallel-1.6.4.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
Collecting dill>=0.3.1
  Downloading dill-0.3.6-py3-none-any.whl (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 KB 1.7 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1 in /usr/local/lib/python3.9/dist-packages (from pandarallel) (1.4.4)
Requirement already satisfied: psutil in /usr/local/lib/python3.9/dist-packages (from pandarallel) (5.9.4)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.9/dist-packages (from pandas>=1->pandarallel) (1.22.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=1->pandarallel) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas>=1->pandarallel) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.8.1->pandas>=1->pandarallel) (1.15.0)
Building wheels for collected packages: pandarallel
  Building wheel for pandarallel (setup.py) ... done
  Created wheel for pandarallel: filename=pandarallel-1.6.4-py3-none-any.whl size=16677 sha256=1498c1563d6a7814e42a9f1ebc9c72e72abd0ada1c20d860bd0a3d89736ac5a1
  Stored in directory: /root/.cache/pip/wheels/41/01/29/deaa71fe596f8d857e57c4fb388db8861e23e6ed0b03204dcb
Successfully built pandarallel
Installing collected packages: dill, pandarallel
Successfully installed dill-0.3.6 pandarallel-1.6.4

In [12]:
from pandarallel import pandarallel
pandarallel.initialize(progress_bar=True)

# Convert x and y (SVY21 coordinates) into Latitude and Longitude
def get_lat_long(row):
    import pyproj
    xfm = pyproj.Transformer.from_crs('EPSG:3414', 'EPSG:4326')
    return xfm.transform(row['y'], row['x'])

merged['lat_long'] = merged.parallel_apply(get_lat_long, axis=1)

INFO: Pandarallel will run on 1 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=23703), Label(value='0 / 23703')))…

Filling property entry with missing x, y coordinates with correct Latitude and Longitude information (from https://www.propertypages.com.sg/condo/condominium-asia-gardens-089394-sglc18173932)

In [13]:
merged[merged.x.isna()]

,street,x,project,y,marketSegment,area,floorRange,noOfUnits,contractDate,typeOfSale,price,propertyType,district,typeOfArea,tenure,lat_long
14251,EVERTON ROAD,NaN,ASIA GARDENS,NaN,RCR,12488,11-15,84,0418,3,343000000,Condominium,02,Strata,Freehold,"(inf, inf)"

In [14]:
merged.loc[14251, 'lat_long'] = (1.276055, 103.838194)

In [15]:
merged[merged.x.isna()]

,street,x,project,y,marketSegment,area,floorRange,noOfUnits,contractDate,typeOfSale,price,propertyType,district,typeOfArea,tenure,lat_long
14251,EVERTON ROAD,NaN,ASIA GARDENS,NaN,RCR,12488,11-15,84,0418,3,343000000,Condominium,02,Strata,Freehold,"(1.276055, 103.838194)"

### Incorporating Nearest MRT data

In [16]:
%pip install xlrd

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xlrd in /usr/local/lib/python3.9/dist-packages (2.0.1)

In [17]:
stations = pd.read_excel('Train Station Codes and Chinese Names.xls') # From LTA DataMall
stations

FileNotFoundError: ignored

In [ ]:
# Dataframe to store MRT station names, latitude and longitude
mrt_df = pd.DataFrame()

# Iterate through station codes to search and store info
for index, row in stations.iterrows():
    station_name = row['mrt_station_english'] + ' mrt station (' + row['stn_code'] + ')'
    station_name = station_name.upper()
    # Common search API to search for MRT stations
    url = "https://developers.onemap.sg/commonapi/search?returnGeom=Y&getAddrDetails=N&searchVal="+station_name
    response = requests.get(url)
    station_data = json.loads(response.text)
    # Normalize and convert to DataFrame
    row_df = pd.json_normalize(station_data, record_path=['results'])
    # Concatenate to the MRT df
    mrt_df = pd.concat([mrt_df, row_df], ignore_index=True)

mrt_df

In [ ]:
# Keep just the Station Name, Latitude and Longitude
mrt_df = mrt_df.rename(columns={'SEARCHVAL':'STATION'}).drop(columns=['X', 'Y', 'LONGTITUDE'])
mrt_df['LATITUDE'], mrt_df['LONGITUDE'] = mrt_df['LATITUDE'].astype(float), mrt_df['LONGITUDE'].astype(float)
mrt_df

In [ ]:
%pip install geopy

In [ ]:
from pandarallel import pandarallel
pandarallel.initialize(progress_bar=True)

# Map nearest MRT to each property
def nearest_mrt(row, stations=mrt_df):
    from geopy.distance import geodesic

    min_distance, nearest_stn, nearest_stn_lat_long = 10000, "", ""
    for stn, stn_lat, stn_long in zip(stations['STATION'], stations['LATITUDE'], stations['LONGITUDE']):
        distance = geodesic(row['lat_long'], (stn_lat, stn_long)).km
        if distance < min_distance:
            min_distance = distance
            nearest_stn = stn
            nearest_stn_lat_long = (stn_lat, stn_long)
    return nearest_stn, min_distance, nearest_stn_lat_long

merged['nearest_mrt'], merged['distance_from_nearest_mrt'], merged['nearest_mrt_lat_long'] = zip(*merged.parallel_apply(nearest_mrt, axis=1))

In [ ]:
from pandarallel import pandarallel
pandarallel.initialize(progress_bar=True)

# Map nearest MRT Station Walking Distance in km and Walking Time in mins
def nearest_mrt_dist_time(row):
    import requests
    import json

    token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEwMDUzLCJ1c2VyX2lkIjoxMDA1MywiZW1haWwiOiJsdWNhc3hrdGFuQGdtYWlsLmNvbSIsImZvcmV2ZXIiOmZhbHNlLCJpc3MiOiJodHRwOlwvXC9vbTIuZGZlLm9uZW1hcC5zZ1wvYXBpXC92MlwvdXNlclwvc2Vzc2lvbiIsImlhdCI6MTY3OTA0NzkzNywiZXhwIjoxNjc5NDc5OTM3LCJuYmYiOjE2NzkwNDc5MzcsImp0aSI6ImVhODkwMjUyZTAxODAyY2E3YzY0NjY3NGZkY2MzNjI3In0.Et7IuEeZ_t35-fdmh-KNTTXC1qf7ICCv6nDutFOJhlw' # Get token from OneMap authentication 
    start = ",".join(str(x) for x in row['lat_long']) 
    end = ",".join(str(x) for x in row['nearest_mrt_lat_long']) 
    url = "https://developers.onemap.sg/privateapi/routingsvc/route?start={}&end={}&routeType=walk&token={}".format(start,end,token)
    response = requests.get(url)
    dist_time_data = json.loads(response.text)

    try:
        time, dist = dist_time_data['route_summary']['total_time'] // 60, dist_time_data['route_summary']['total_distance'] // 1000
    except:
        time, dist = None, None
        
    return time, dist

merged['nearest_mrt_walking_time'], merged['nearest_mrt_walking_distance'] = zip(*merged.parallel_apply(nearest_mrt_dist_time, axis=1))

In [ ]:
merged

In [ ]:
# Save DataFrame to a csv
merged.to_csv('Private Residential Property Transactions with MRT Data.csv', index=False)

In [ ]:
# Read csv to check data
df = pd.read_csv('Private Residential Property Transactions with MRT Data.csv')
df